// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okmwzhohwuunqbfbruru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rbXd6aG9od3V1bnFiZmJydXJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMyMDc0NjAsImV4cCI6MjA4ODc4MzQ2MH0.BxlPCXBEnCFnYwehbYHPTNsAIsWxtqx1O3i-6WQVfG0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});